### ISSUE TITLE
Not publishing in inappbrowser cordova ionic

### ISSUE THREAD

**Issue by jamils82** [opentok/opentok-video-call-center#1]
Hello i trying to call this in my inappbrowser but its not accessing camera.I am getting an error.
Any solution?
Thanks in advance
![screenshot_2018-08-15-10-07-16 1](https://user-images.githubusercontent.com/20075485/44302085-ca771580-a33b-11e8-925f-803952e7214b.png)

**Comment by MichaelJolley** [comment]
@jamils82 Not sure if you're still having this issue, but this repo was not setup for Cordova. You'd likely need to be using the client SDK and requesting permission to access devices in your application.
