### ISSUE TITLE
Issue with join as a agent 

### ISSUE THREAD

**Issue by Loks2008** [opentok/opentok-video-call-center#3]
I cannot connect with the agent no matter what. I am able to bring up the caller screen with "Waiting for agent to join…" only after that nothing happens. In the agent screen i am receiving "No callers connected" always.  Please kindly help me out.

**Comment by kopi-kosong** [comment]
Hi, i seem to have the same issue. By any chance, you resolved it?

**Comment by vieyrapy** [comment]
Hola tengo el mismo problema

**Comment by riq** [comment]
Make sure to enable session monitoring and check that the callback uri is working

> Register session monitoring callback in your TokBox account for the path /ot_callback. For example, if this application is hosted at https://example.com, register this URL: https://example.com/ot_callback.

**Comment by kopi-kosong** [comment]
Hi, 

i am still facing the issue that caller UI shows "Waiting for agent to join…". I did try to configure callback URL from my account -> my project -> "project settings".  As i noticed in the URL there is a "#". For example, my application's URL is , https://<mydomain>/#/agent. So when i tried to configured the callback, i also firstly configured it as https://<mydomain>/#/ot_callback. However it was not working. Then i changed it to a URL without "#". it became https://<mydomain>/ot_callback/, but if it did not work either. Could you please help to give some advice on this?

Thank you.

**Comment by kopi-kosong** [comment]
Thank you. After configuring the URL, it is working for me now.

**Comment by MichaelJolley** [comment]
@riq is correct. That should resolve this issue. Thanks!
