### ISSUE TITLE
No callers connected

### ISSUE THREAD

**Issue by vieyrapy** [opentok/opentok-video-call-center#5]
Hola he terminado de hacer deploy en heroku y he creado varios clientes, pero en la sección de agentes no me en lista ninguno. También no he podido localizar la sección donde se da de alta a un agente.

**Comment by MichaelJolley** [comment]
Hi @vieyrapy, be sure to register the session monitoring callback:

> Register session monitoring callback in your TokBox account for the path /ot_callback. For example, if this application is hosted at https://example.com, register this URL: https://example.com/ot_callback.
